madflojo/automatron

plugins/vetting/ontarget/system_info.py
=> Adding ip interface facts

plugins/vetting/ontarget/system_info.py
Reverts madflojo/automatron#25
=> Revert "Adding ip interface facts"

plugins/vetting/ontarget/system_info.py
Reverts madflojo/automatron#26
=> Revert "Revert "Adding ip interface facts""

actioning.py, config/runbooks/examples/disk_free/init.yml
Oversight in logic made it to where actions are run regardless of check result
=> Revising should I run logic

plugins/vetting/ontarget/services.py
Captures status of services on Linux targets. 
Closes #23
=> Service facts

README.md, docs/runbooks/runbooks.md
* Added full path to Automatron Logo
* Added Docker link to Next Steps
=> Documentation on README.md

plugins/discovery/digitalocean/__init__.py, plugins/discovery/nmap/__init__.py, plugins/discovery/webping/__init__.py, runbooks.py
Moved several `info` messages to `debug`
=> Revising logging verbosity

plugins/discovery/aws/__init__.py, requirements.txt
=> AWS Autodiscovery plugin

config/config.yml.example, plugins/discovery/digitalocean/__init__.py, plugins/discovery/linode/__init__.py, tests/unit/test_plugins_discovery_digitalocean_discover.py, tests/unit/test_plugins_discovery_linode_discover.py
This PR adds a plugin for automatic discovery of Linode nodes.
=> Linode autodiscovery

CONTRIBUTING.md
Creates a contribution guide and general developer guide.
=> Adding Contribution guide

docs/plugins/discovery/roster.md, mkdocs.yml, plugins/discovery/roster/__init__.py, tests/unit/test_plugins_discovery_roster_discover.py
Adds the ability to specify hosts via the master Automatron configuration file.
Includes:
* Plugin
* Documentation
* Unit Tests
=> Adding a Roster file based Discovery plugin

Dockerfile, config/config.yml.example, docs/index.md, docs/plugins/discovery/aws.md, docs/plugins/discovery/digitalocean.md, docs/plugins/discovery/linode.md, mkdocs.yml
Includes:
* Missing AWS Discovery Plugin docs
* Missing Linode Discovery Plugin docs
* Corrections to DigitalOcean Plugin docs
* Minor correction to Overview
* Examples added to `config.yml.example`
=> Documentation true up

runbooks.py, tests/integration/test_runbooks_render_runbooks.py
Found issue with Automatron crashing when Jinja templates have errors. This should fix it for runbook rendering.
=> Runbook render exceptions

actioning.py, docs/runbooks.md, monitoring.py, tests/unit/test_actioning_execute_runbook.py
This PR adds the ability to target specific hosts during action execution.
=> Adding target hosts while executing actions.

docs/facts.md, docs/plugins/actions.md, docs/plugins/checks.md, mkdocs.yml
This pull request adds documentation about creating custom health check and action plugins.
=> Plugin documentation

static/js/automatron.js
Found a bug when the API returns health checks that have never run.
=> Adding object attribute checking to javascript parser of API data

runbooks.py, tests/unit/test_runbooks_cache_runbooks.py
Also added some tests for this scenario.
=> Fixing handling of malformed runbooks/init.yml files

actioning.py, static/js/automatron.js, templates/index.html, tests/unit/test_actioning_update_target_status.py
This PR adds a simple Server information modal to the dashboard. When you click the title of the found servers the following modal will popup.
=> Adding server info modal to dashboard

docker-compose.yml, docs/configure.md, docs/install/docker.md, docs/install/index.md
* Fixing the Webping port in the documentation
* Fixing the UI port in the documentation
=> Fixing some simple documentation based on issue #115 feedback

Dockerfile, actioning.py, docs/runbooks/actions.md, requirements.txt
Adding the "run_once" action flag in the actioning.py file.
Adding the documentation of the flag documentation to current docs.
Adding the fabric version fix to requirements (should that go on current version?)
=> Run once feature
